
export var all = [
{ name: "after dinner cream mints 20pk (js)	", total : 1 },
{ name: "andrex quilts x9	", total : 4 },
{ name: "apple bramley lse	", total : 2 },
{ name: "asparagus spears (js)	", total : 1 },
{ name: "asparagus tips (js)	", total : 4 },
{ name: "b/e petits pois 1.28k	", total : 4 },
{ name: "bacofoil non-stick	", total : 3 },
{ name: "baked beans (js)	", total : 1 },
{ name: "baked beans x4 (js)	", total : 3 },
{ name: "banana fairtrade LSE	", total : 8 },
{ name: "baps ttd multiseed	", total : 1 },
{ name: "basil (js)	", total : 1 },
{ name: "beef paste 75g (js)	", total : 1 },
{ name: "birds eye omega fish fingers 20	", total : 1 },
{ name: "black pudding (js)	", total : 2 },
{ name: "bloo blk aqau rf x1	", total : 2 },
{ name: "blossom hill rose	", total : 1 },
{ name: "blue stilton 220g (js)	", total : 1 },
{ name: "bouquet garni 5g (js)	", total : 1 },
{ name: "bread white batch (js)	", total : 13 },
{ name: "brit mature cheddar (js)	", total : 8 },
{ name: "broccoli loose	", total : 3 },
{ name: "broccoli prepacked (js)	", total : 2 },
{ name: "buckwud maple syrup	", total : 2 },
{ name: "cabbage so org sweetheart	", total : 2 },
{ name: "cabbage sweetheart (js)	", total : 1 },
{ name: "cadbury mini eggs bag	", total : 1 },
{ name: "campbells condensed mushroom	", total : 1 },
{ name: "carrots bunch organic so	", total : 1 },
{ name: "carrots chantenay (js)	", total : 1 },
{ name: "carrots loose	", total : 2 },
{ name: "carrots ttd swt spr	", total : 1 },
{ name: "cauliflower	", total : 3 },
{ name: "celebrations large egg	", total : 1 },
{ name: "celery 450g (js)	", total : 1 },
{ name: "cherries bll glc	", total : 1 },
{ name: "chicken and mushroom slice	", total : 1 },
{ name: "chrysanths	", total : 1 },
{ name: "clarks original maple syrup	", total : 1 },
{ name: "clover	", total : 1 },
{ name: "clynomyn toothpaste	", total : 1 },
{ name: "cocktail sausages sa 12 ttd	", total : 1 },
{ name: "colemans bread sauce 40g	", total : 1 },
{ name: "colemans parsley sauce	", total : 1 },
{ name: "coleslaw basics	", total : 1 },
{ name: "comfort blue skies	", total : 1 },
{ name: "corned beef w/onion	", total : 1 },
{ name: "crab spread	", total : 1 },
{ name: "cricket firepower	", total : 1 },
{ name: "crisp peking duck	", total : 1 },
{ name: "cucumber whole	", total : 1 },
{ name: "d/s bin bag x20 (js)	", total : 1 },
{ name: "del monte pineapple	", total : 1 },
{ name: "dishwasher tablets x30 basics	", total : 1 },
{ name: "double cream (js)	", total : 3 },
{ name: "double cream extra thick (js)	", total : 3 },
{ name: "eggs large x6	", total : 1 },
{ name: "eggs x12 (js)	", total : 5 },
{ name: "elizabeth shaw mint crisp	", total : 1 },
{ name: "elmlea double	", total : 7 },
{ name: "elnett hair spray	", total : 1 },
{ name: "extra fine beans (js)	", total : 4 },
{ name: "fairy nonbio powder	", total : 1 },
{ name: "fine beans (js)	", total : 1 },
{ name: "fish pie mix (js)	", total : 1 },
{ name: "freezer bags x40 (js)	", total : 1 },
{ name: "gammon joint smoked (js)	", total : 1 },
{ name: "garlic bulb single	", total : 1 },
{ name: "glenryck pilchards t	", total : 2 },
{ name: "greeting card (js)	", total : 4 },
{ name: "ground mixed spice (js)	", total : 2 },
{ name: "halls mints x9	", total : 5 },
{ name: "ham carvery (js)	", total : 1 },
{ name: "heinz salad cream	", total : 1 },
{ name: "honey roast ham (js)	", total : 15 },
{ name: "hot cross buns ttd	", total : 1 },
{ name: "hovis seed sensation 7seeds 800g	", total : 12 },
{ name: "hovis wheatgerm 400g	", total : 9 },
{ name: "hovis wholemeal seed sensation 7seeds 800g	", total : 1 },
{ name: "hp brown sauce 600g	", total : 1 },
{ name: "icbin butter	", total : 4 },
{ name: "icbin butter 500g	", total : 6 },
{ name: "jus roll puff pastry	", total : 7 },
{ name: "king prawns 155g (js)	", total : 1 },
{ name: "kipper fillets ttd	", total : 1 },
{ name: "kitchen towel x3 (js)	", total : 2 },
{ name: "knorr chicken cube	", total : 1 },
{ name: "lard 250g (js)	", total : 2 },
{ name: "laughing cows triangles	", total : 1 },
{ name: "lemon single	", total : 1 },
{ name: "lemons single	", total : 1 },
{ name: "lettuce iceberg	", total : 1 },
{ name: "lettuce iceberg (js)	", total : 1 },
{ name: "lettuce little gem x2 (js)	", total : 3 },
{ name: "lurpak spreadable	", total : 12 },
{ name: "mackerel fillets cw	", total : 1 },
{ name: "mackerel pate (js)	", total : 4 },
{ name: "majoram (js)	", total : 1 },
{ name: "malteasers large egg	", total : 1 },
{ name: "marmite 250g	", total : 2 },
{ name: "mars 9 pack	", total : 3 },
{ name: "mccain straight cut chips	", total : 3 },
{ name: "mcdougal plain flour	", total : 2 },
{ name: "mcdougal self reaising flour	", total : 1 },
{ name: "mcvities rich tea	", total : 3 },
{ name: "melon cantaloupe	", total : 1 },
{ name: "mild curry powder (js)	", total : 1 },
{ name: "milk s/skim 2.272L	", total : 5 },
{ name: "mini potatoes 750g	", total : 1 },
{ name: "mint jelly (js)	", total : 1 },
{ name: "mushroom baby button 200 (js)	", total : 1 },
{ name: "mushroom small chestnut (js)	", total : 1 },
{ name: "mushy processed peas	", total : 2 },
{ name: "mustard colman eng	", total : 3 },
{ name: "naan garlic/coriander x2	", total : 1 },
{ name: "napaloni tomato chopped 4x400g	", total : 1 },
{ name: "nescafe gold blend 300g	", total : 3 },
{ name: "nivea creme	", total : 1 },
{ name: "olbas oil 28ml	", total : 1 },
{ name: "olives & manchego (js)	", total : 1 },
{ name: "onion	", total : 7 },
{ name: "onion spring bunch	", total : 2 },
{ name: "onion spring large bunch	", total : 3 },
{ name: "oxo cubes red	", total : 1 },
{ name: "oxo red salt beef cubes	", total : 1 },
{ name: "pantene 2 in 1	", total : 1 },
{ name: "parsley curley leaf plant (js)	", total : 1 },
{ name: "parsley sauce	", total : 1 },
{ name: "pear r&r conference x4	", total : 1 },
{ name: "pear r&r x4	", total : 4 },
{ name: "pek chopped pork	", total : 2 },
{ name: "pek gold pork	", total : 1 },
{ name: "pepper green	", total : 1 },
{ name: "pepper orange	", total : 3 },
{ name: "pepper red	", total : 1 },
{ name: "pork sausages bc 12 (js)	", total : 1 },
{ name: "potatoes baking	", total : 14 },
{ name: "potatoes easy peeler 1KG	", total : 1 },
{ name: "potatoes mini 750g	", total : 1 },
{ name: "princes salmon paste	", total : 1 },
{ name: "prunes in juice	", total : 1 },
{ name: "rectangular dish (js)	", total : 1 },
{ name: "recurrant jelly (js)	", total : 1 },
{ name: "red salmon 213g	", total : 1 },
{ name: "richmond pork sausages	", total : 3 },
{ name: "richmond sausages thick	", total : 1 },
{ name: "rinse aid	", total : 1 },
{ name: "roll cheese topped x4 (js)	", total : 4 },
{ name: "rummo fusilli	", total : 1 },
{ name: "runner beans (js)	", total : 1 },
{ name: "sacla pesto	", total : 1 },
{ name: "sage (js)	", total : 1 },
{ name: "salmon (js) & chilli	", total : 2 },
{ name: "salmon fillets	", total : 3 },
{ name: "schwartz creamy parsley sauce	", total : 1 },
{ name: "simple soap 4x125g	", total : 1 },
{ name: "sizzler danish smoked bacon	", total : 1 },
{ name: "smoked bacon basics (js)	", total : 1 },
{ name: "smoked cod loins	", total : 1 },
{ name: "sponge fingers (js)	", total : 1 },
{ name: "sugar granulated (js)	", total : 1 },
{ name: "sultanas 1kg (js)	", total : 1 },
{ name: "swede (js)	", total : 1 },
{ name: "tea bags yorkshire 240	", total : 4 },
{ name: "tena lady mini	", total : 1 },
{ name: "tomato beef single	", total : 1 },
{ name: "tomato cherry 335g (js)	", total : 1 },
{ name: "tomato ttd pomodorino	", total : 1 },
{ name: "tomato ttd vittoria	", total : 4 },
{ name: "tomato vine	", total : 1 },
{ name: "tptre orange&tango 454g	", total : 1 },
{ name: "tradition beetroot (js)	", total : 1 },
{ name: "trifle sponges (js)	", total : 1 },
{ name: "tropicana classics 950ml	", total : 1 },
{ name: "uncle bens long grain rice 2kg	", total : 1 },
{ name: "vac pack beetroot (js)	", total : 1 },
{ name: "vanish gold powder	", total : 1 },
{ name: "walkers crisps x6 cheese/onion	", total : 5 },
{ name: "warburtons honey wheat	", total : 1 },
{ name: "warburtons seeded batch	", total : 1 },
{ name: "warburtons wholemeal 400g	", total : 1 },
{ name: "washing up liq sensitive	", total : 2 },
{ name: "werthers sugar free	", total : 2 },
{ name: "wholemeal 400g	", total : 1 },
{ name: "yeo valley blueberry yoghurt	", total : 2 },
];


export var filtered = [
{ name: "after dinner cream mints 20pk (js)	", total : 1 },
{ name: "andrex quilts x9	", total : 4 },
{ name: "apple bramley lse	", total : 2 },
{ name: "asparagus spears (js)	", total : 1 },
{ name: "asparagus tips (js)	", total : 4 },
];
